# Example format - to be updated with details for destination Linux machine

ip-address =
  # Add IP address here
username =
  # Add destination machine username here
password =
  # Add destination machine password here
filepath =
  # Add the path to the local directory containing the packet captures here
